### ISSUE TITLE
Could not use apoc procedure

### ISSUE THREAD

**Issue by thegallier** [tomasonjo/blogs#11]
Used a url that worked with GraphDatabase.  It is throwing the above error.  I changed some settings in neo4j.conf.  It seems it also requires now an apoc.conf that I put in same directory as neo4j.conf   It contains apoc.export.file.enabled=true.  When I ask to show procedures the apoc.meta.data does not show.  Did u do a config wrong or is there a way to use the GraphDatabase (which works).  I am trying to use the vector database .

thanks

**Comment by thegallier** [comment]
The routine that throws the error is Neo4Graph in langchain.graphs

**Comment by tomasonjo** [comment]
You need to install APOC Core plugin

**Comment by thegallier** [comment]
Actually I am good.  I had to remove the old plugin.  And have changed some settings.  Thanks.
