### ISSUE TITLE
Embedding similarity search

### ISSUE THREAD

**Issue by thegallier** [tomasonjo/blogs#12]
I created a vector index with a hugging face embedding.  I see the embeddings in the graph.  The vector_index.similarity_search always returns an empty response.  Embeddings.embed_query does give a vector.  Am I missing something?

**Comment by thegallier** [comment]
This does look like faiss under the hood.  Do you give access to the faiss index?

**Comment by thegallier** [comment]
I think Neo4jVector.from works with hugging face embeddings but the search does not.  So I for the moment just create my own index outside of neo4j.  I guess I will then have to duplicate some of the functionality to combine it with cypher.

**Comment by tomasonjo** [comment]
Have you used multiple different embeddings before? The search should work exactly as the embedding does, what kind of setting are you using?

**Comment by thegallier** [comment]
That is the surprise.  Most of the queries return empty, but I have seen an error message that said hugging face embeddings not supported.  To be clear I used one of your post where you did db.similarity_search tried most of the others too.  When I just retrieve the embeddings from graph.query and insert in my own faiss flat2index that works.  So way into neo4j is good.  I am using 5.12

**Comment by tomasonjo** [comment]
That's weird, either all queires should be empty or none, can you share your code so that I can reproduce this error on my end?

**Comment by thegallier** [comment]
well as mentioned all returned empty list (except when i modified your example, one error gave HuggingFace embeddings not supported)
Here is what I can share
from langchain.embeddings import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings(modelname=model_name)

vector_index=Neo4jVector.from_existing_graph(embeddings,url,username,password,index_name,node_label,text_node_properties=[],embedding_node_property='embedding')

so if i then go and look at the nodes the embeddings are there

query="Some text" 
docs=vector_index.similarity_search(query,k=2)

results in empty docs.

I tried other searches inclusive the vector one.  No luck.  For those I have made mistakes.  But I did start from one of your examples.

/==
res = graph.query("""
                               MATCH (n)
                               RETURN n.embedding as embeddings
"""
import faiss
index=faiss.IndexFlatL2(d)

and then index.add
of an an np array casted to np.float32 coming from the above.

results = index.search(np.array(embeddings.embed_query("Some Query")  casted etc.

that works.


Thanks for all the work!  A graph database integrated with an LLM does make sense for what I am doing.

vector_index

**Comment by tomasonjo** [comment]
The problem is that you are using an empty list for node properties?

text_node_properties=[]

**Comment by thegallier** [comment]
no it has 2 properties in it.

**Comment by thegallier** [comment]
otherwise i could not have created the embeddings vectors right?  and the faiss search confirms that they are relevant

**Comment by thegallier** [comment]
if you confirm an example that works with the HuggingFace embeddings I can check again.  For this portion shouldn't just be
from langchain.embeddings import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings(model_name=SomeModelName) #replace with your choice

then that goes in your example instead of the OpenAI one?  I guess I can confirm that the embeddings work but I have trouble with the search (left alone integration in cypher)

**Comment by tomasonjo** [comment]
We tested multiple embedding settings in the genai project and they all
work without any problem:
https://github.com/docker/genai-stack/blob/main/chains.py#L16

**Comment by thegallier** [comment]
Perfect.  Let me try that.  Thank you.

**Comment by thegallier** [comment]
Works.  It was the index that was the issue.
