### ISSUE TITLE
:loudspeaker: Create a "social media preview" for this amazing repo :art: 

### ISSUE THREAD

**Issue by adriens** [tomasonjo/blogs#13]
# :grey_question: About

This repo is an awesome source of knowledge and inspiration. Still, while wanting to share it on social networks, the preview seems poor regarding the potential it has : 

![image](https://github.com/tomasonjo/blogs/assets/5235127/8237a0c6-0ba8-4397-acdf-c8692bc848d9)

# :dart: Action

Designing and setting a ["social media preview"](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) would be a great way to achieve this :star_struck:

**Comment by tomasonjo** [comment]
done
