### ISSUE TITLE
DevOp RAg

### ISSUE THREAD

**Issue by mars203030** [tomasonjo/blogs#17]
Hey,

it seems this code is not working , it does not generate embedding  in the databse ? is there a special configuration I need to do?
it does generate a vector index
`

vector_index = Neo4jVector.from_existing_graph(
    OpenAIEmbeddings(),
    url=url,
    username=username,
    password=password,
database='sss',
    index_name='tasks',
    node_label="Task",
    text_node_properties=['name', 'description', 'status'],
    embedding_node_property='embedding',
)`

**Comment by tomasonjo** [comment]
It should calculate embeddings if any of the node properties are not null

**Comment by mars203030** [comment]
Hey Thanks, it worked ,, I am not sure what was the problem I redid it again and it worked
