### ISSUE TITLE
how to get bolt url for aura neo4j instance?

### ISSUE THREAD

**Issue by rawwerks** [tomasonjo/blogs#26]
@tomasonjo - sorry for the n00b question, but how do i get the bolt address of my aura neo4j instance?

https://github.com/tomasonjo/blogs/blob/8289fc3272625de35974ed355db44fa1c58a4e09/llm/llama_index_neo4j_custom_retriever.ipynb#L93C1-L93C46

in console, i only see 

`neo4j+s://myhash.databases.neo4j.io`

...which doesn't work if i put that as the url in your notebook: https://github.com/tomasonjo/blogs/blob/master/llm/llama_index_neo4j_custom_retriever.ipynb

**Comment by tomasonjo** [comment]
It should work, what is the error?

**Comment by rawwerks** [comment]
`ServiceUnavailable: Unable to retrieve routing information`

**Comment by rawwerks** [comment]
the llamaindex source only includes a local example too: https://github.com/run-llama/llama_index/blob/8e46df7baf8440ac14f4be2ce75c3872584addff/llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py#L111

**Comment by rawwerks** [comment]
https://github.com/run-llama/llama_index/issues/14225
