### ISSUE TITLE
Dataset details 

### ISSUE THREAD

**Issue by Tijana37** [tomasonjo/blogs#31]
Using script: https://github.com/tomasonjo/blogs/blob/master/llm/graph_based_prefiltering.ipynb <br>
It is not clear which dataset was used. Could you provide a link from Neo4j Datasets ?

**Comment by tomasonjo** [comment]
https://medium.com/neo4j/graph-based-metadata-filtering-for-improving-vector-search-in-rag-applications-47fd2efcfc0a


Its a public demo db
