### ISSUE TITLE
The 'Importing Communities' section in ms_graphrag_import.ipynb doesn't seem quite right.

### ISSUE THREAD

**Issue by DequanZhu** [tomasonjo/blogs#40]
While reviewing the contents of create_final_communities.parquet, I noticed that for each community, the text_unit_ids is a list. Upon further inspection, I found that each element in the list is not a single UUID string but a string made up of multiple UUIDs separated by commas.
![image](https://github.com/user-attachments/assets/cfc2a4ed-8f58-46bf-8bfd-c5441527abcb)
In the 'Importing Communities' section of the notebook at https://github.com/tomasonjo/blogs/blob/master/msft_graphrag/ms_graphrag_import.ipynb, it seems that the text_unit_id is a string of multiple UUIDs joined by commas, rather than a single UUID. This doesn't seem to align with the intended meaning of text_unit_id. Is this the expected behavior?
![image](https://github.com/user-attachments/assets/ff0ed990-ec08-442f-be04-8c38374ec334)

**Comment by tomasonjo** [comment]
You can see that it's commented out and we use relationship ids
