### ISSUE TITLE
error  built-in class

### ISSUE THREAD

**Issue by nawara72** [tomasonjo/blogs#6]
Hi

I tried running the code but I get the following error
<class '__main__.RebelComponent'> is a built-in class

Would really appreciate your help in sorting it out. Thanks

**Comment by tomasonjo** [comment]
Did you run this code twice?
I think this error appears on the second run, however a single is enough?

**Comment by nawara72** [comment]
Thank u so much for quick reply and yes that worked perfectly now.

Thanks again
